---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by v_0ver.
--- DateTime: 10/8/19 8:45 PM
---

require "Utils"


BondsTickerList = {}
classCode = "TQOB"

IsRun = true;

local function CreateTable()
    t_id = AllocTable()
    AddColumn(t_id, 0, "Бумага", true, QTABLE_STRING_TYPE, 15)

    AddColumn(t_id, 1, "пред. с/в цена, %", true, QTABLE_DOUBLE_TYPE, 8)
    AddColumn(t_id, 2, "с/в цена, %", true, QTABLE_DOUBLE_TYPE, 8)

    AddColumn(t_id, 3, "пред. с/в дох., %", true, QTABLE_DOUBLE_TYPE, 15)
    AddColumn(t_id, 4, "с/в дох., %", true, QTABLE_DOUBLE_TYPE, 15)

    AddColumn(t_id, 5, "LOW, %", true, QTABLE_DOUBLE_TYPE, 15)
    AddColumn(t_id, 6, "HIGH, %", true, QTABLE_DOUBLE_TYPE, 15)

    AddColumn(t_id, 7, "цел. цена, %", true, QTABLE_DOUBLE_TYPE, 15)

    AddColumn(t_id, 8, "Дюрация, лет", true, QTABLE_DOUBLE_TYPE, 15)
    AddColumn(t_id, 9, "Купон, %", true, QTABLE_DOUBLE_TYPE, 8)
    AddColumn(t_id, 10, "Погашение", true, QTABLE_STRING_TYPE, 15)


    t = CreateWindow(t_id)
    SetWindowCaption(t_id, "Облигации")
end




function OnInit()
    CreateTable()
    arr = {}
    sec_list = getClassSecurities(classCode)
    sec_listTable = string.split(sec_list, ',')

    for j = 1, #arr do
        row = InsertRow(t_id, -1)
    end
end;

function main()
   while IsRun do

        j = 0
        for i = 1, #sec_listTable do
            secCode = sec_listTable[i]
            securityInfo = getSecurityInfo(classCode, secCode)
            short_name = securityInfo.short_name

            j = j + 1
            r = {}
            r["short_name"] = short_name
            r["waprice"] = getParamNumber(securityInfo.code, "WAPRICE")
            r["wayield"] = getParamNumber(securityInfo.code, "YIELDATWAPRICE")
            r["prevwaprice"] = getParamNumber(securityInfo.code, "PREVWAPRICE")
            r["prevwayield"] = getParamNumber(securityInfo.code, "YIELDATPREVWAPRICE")

            r["low"] = getParamNumber(securityInfo.code, "LOW")
            r["high"] = getParamNumber(securityInfo.code, "HIGH")

            r["duration"] = getParamNumber(securityInfo.code, "DURATION")/365
            couponvalue = getParamNumber(securityInfo.code, "COUPONVALUE")
            couponperiod = getParamNumber(securityInfo.code, "COUPONPERIOD")
            r["coupon"] = ((365/couponperiod) * couponvalue)/10
            r["mat_date"] = getParamNumber(securityInfo.code, "MAT_DATE")

            r["nowprice"] = getParamNumber(securityInfo.code, "PRICE")

            table.insert(arr, j, r)

        end

        for j = 1, #arr do
            row =  GetRow  InsertRow(t_id, -1)
            SetCell(t_id, row, 0, arr[j]["short_name"])

            prevwaprice = arr[j]["prevwaprice"]
            SetCell(t_id, row, 1, string.format("%.2f", prevwaprice), prevwaprice)

            waprice = arr[j]["waprice"]
            SetCell(t_id, row, 2, string.format("%.2f", waprice), waprice)

            prevwayield = arr[j]["prevwayield"]
            SetCell(t_id, row, 3, string.format("%.2f", prevwayield), prevwayield)

            wayield = arr[j]["wayield"]
            SetCell(t_id, row, 4, string.format("%.2f", wayield), wayield)

            low = arr[j]["low"]
            SetCell(t_id, row, 5, string.format("%.2f", low), low)

            high = arr[j]["high"]
            SetCell(t_id, row, 6, string.format("%.2f", high), high)

            target = math.min(prevwaprice,waprice)*0.999
            SetCell(t_id, row, 7, string.format("%.2f", target), target)

            duration = arr[j]["duration"]
            SetCell(t_id, row, 8, string.format("%.2f", duration), duration)
            coupon = arr[j]["coupon"]
            SetCell(t_id, row, 9, string.format("%.2f", coupon), coupon)
            mat_date = arr[j]["mat_date"]
            SetCell(t_id, row, 10, formatData(mat_date), mat_date)


        end


   sleep(1);
   end;
end;

function OnStop()

   IsRun = false;
end;

--https://quikluacsharp.ru/quik-qlua/proverka-vystavleniya-zayavki-po-otpravlennoj-tranzaktsii-qlua-lua/