---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by v_0ver.
--- DateTime: 10/8/19 9:15 PM
---


function getParamNumber(code, param)
    return tonumber(getParamEx(classCode, code, param).param_value)
end

function string.split(str, sep)
    local fields = {}
    str:gsub(string.format("([^%s]+)", sep), function(f_c) fields[#fields + 1] = f_c end)
    return fields
end

function formatData(prm)
    return string.format("%02d.%02d.%04d", prm%100, (prm%10000)/100, prm/10000)
end